name: Build

on:
  push:
    branches: [ mod ]
  pull_request:
    branches: [ mod ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Build project for Windows
        run: npm run build:electron:windows
      - name: Upload Windows build
        uses: actions/upload-artifact@v2.2.4
        with:
          name: JellMachinePlus_win
          path: dist/Jell Machine Plus-win32-x64
          if-no-files-found: error
      - name: Build project for Linux
        run: npm run build:electron:linux
      - name: Upload Linux build
        uses: actions/upload-artifact@v2.2.4
        with:
          name: JellMachinePlus_linux
          path: dist/Jell Machine Plus-linux-x64
          if-no-files-found: error
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Build project for Mac
        run: |
          npm run build:electron:mac
          chmod a+x "dist/Jell Machine Plus-darwin-x64/Jell Machine Plus.app/Contents/MacOS/Jell Machine Plus"
          cd dist/Jell\ Machine\ Plus-darwin-x64
          tar -cvf ../MacOS.tar Jell\ Machine\ Plus.app
          cd ../..
      - name: Upload Mac build
        uses: actions/upload-artifact@v2.2.4
        with:
          name: JellMachinePlus_mac
          path: dist/MacOS.tar
          if-no-files-found: error
